### ISSUE TITLE
Does not support PostSharp 6.0

### ISSUE THREAD

**Issue by ArvinHsieh** [postsharp/PostSharp.LicenseServer#5]
The last version 5.0.33 cannot support PostSharp 6.0 in VS2017. Is it possible to upgrade the supported version? Thanks.

**Comment by prochan2** [comment]
The latest version supports all supported versions of PostSharp including PostSharp 6.0. If you're experiencing any issues, please contact us via https://www.postsharp.net/support and include all details of the issues and license number(s) of the licence(s) registered on your license server. License number is the number in the beginning of a license key followed by a dash.
